name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Front-end Dependencies
      run: npm install
      working-directory: ./front-end

    - name: Run Front-end Lint
      run: npm run lint
      working-directory: ./front-end

    - name: Run Front-end Build
      run: npm run build
      working-directory: ./front-end

    - name: Install Back-end Dependencies
      run: npm install
      working-directory: ./back-end

    - name: Run Back-end Lint
      run: npm run lint
      working-directory: ./back-end

    - name: Run Back-end Build
      run: npm run build
      working-directory: ./back-end

    - name: Run Back-end Tests
      run: npm test
      working-directory: ./back-end
